#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
管道 1: CSV 自动分析器
======================
filesystem 发现 CSV → duckdb 分析 → filesystem 写入报告

用法:
  python pipeline_csv_analyzer.py /path/to/dir [--output report.md]
  python pipeline_csv_analyzer.py . --top 10

零 MCP 依赖，直接调用 duckdb Python API 和 os 模块。
"""
import os, sys, json, argparse
from pathlib import Path
from datetime import datetime
import duckdb


def find_csv_files(root: str) -> list[Path]:
    """filesystem.search_files 的 Python 等价实现"""
    csvs = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if not d.startswith(".") and d != "node_modules"]
        for f in filenames:
            if f.lower().endswith(".csv"):
                csvs.append(Path(dirpath) / f)
    return csvs


def analyze_csv(filepath: Path) -> dict:
    """duckdb 分析单个 CSV"""
    try:
        con = duckdb.connect(":memory:")
        abs_path = str(filepath.resolve()).replace("\\", "/")
        con.execute(f"CREATE TABLE tmp AS SELECT * FROM read_csv_auto('{abs_path}')")

        cols = con.execute("SELECT column_name, data_type FROM information_schema.columns WHERE table_name='tmp'").fetchall()
        row_count = con.execute("SELECT count(*) FROM tmp").fetchone()[0]

        # 数值列的统计摘要
        num_cols = [c[0] for c in cols if c[1] in ("INTEGER", "BIGINT", "DOUBLE", "FLOAT", "DECIMAL")]
        stats = {}
        for nc in num_cols[:10]:  # 最多 10 个数值列
            try:
                s = con.execute(f"""
                    SELECT min("{nc}"), max("{nc}"), avg("{nc}"), median("{nc}"), stddev("{nc}")
                    FROM tmp WHERE "{nc}" IS NOT NULL
                """).fetchone()
                stats[nc] = {"min": s[0], "max": s[1], "avg": round(s[2], 2) if s[2] else None,
                             "median": round(s[3], 2) if s[3] else None, "stddev": round(s[4], 2) if s[4] else None}
            except Exception:
                pass

        con.close()
        return {"file": str(filepath), "rows": row_count, "columns": len(cols),
                "column_names": [c[0] for c in cols][:20], "stats": stats, "ok": True}
    except Exception as e:
        return {"file": str(filepath), "error": str(e), "ok": False}


def generate_report(results: list[dict]) -> str:
    """生成 Markdown 报告"""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    ok = [r for r in results if r["ok"]]
    err = [r for r in results if not r["ok"]]

    lines = [
        f"# CSV Analysis Report",
        f"**Generated**: {now}",
        f"**Total CSVs found**: {len(results)}  |  **Analyzed**: {len(ok)}  |  **Failed**: {len(err)}",
        "",
        "---",
        "",
    ]

    for r in ok:
        lines.append(f"## {Path(r['file']).name}")
        lines.append(f"- **Path**: `{r['file']}`")
        lines.append(f"- **Rows**: {r['rows']:,}  |  **Columns**: {r['columns']}")
        lines.append(f"- **Columns**: {', '.join(r['column_names'])}")
        if r.get("stats"):
            lines.append("")
            lines.append("| Column | Min | Max | Avg | Median | StdDev |")
            lines.append("|--------|-----|-----|-----|--------|--------|")
            for col, s in r["stats"].items():
                lines.append(f"| {col} | {s['min']} | {s['max']} | {s['avg']} | {s['median']} | {s['stddev']} |")
        lines.append("")

    if err:
        lines.append("## Failed")
        for e in err:
            lines.append(f"- `{e['file']}`: {e['error']}")
        lines.append("")

    lines.append("---")
    lines.append(f"*Report generated by DEEPCODE pipeline_csv_analyzer.py*")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="CSV Auto Analyzer Pipeline")
    parser.add_argument("path", help="Directory to scan for CSV files")
    parser.add_argument("--output", "-o", default="csv_report.md", help="Output report path")
    parser.add_argument("--top", type=int, default=0, help="Only analyze top N CSVs (by row count)")
    args = parser.parse_args()

    root = Path(args.path).resolve()
    if not root.is_dir():
        print(f"Error: {root} is not a directory")
        sys.exit(1)

    print(f"[1/3] Scanning {root} for CSV files...")
    csvs = find_csv_files(str(root))
    print(f"       Found {len(csvs)} CSV files")

    if not csvs:
        print("       No CSV files found, exiting.")
        return

    print(f"[2/3] Analyzing with duckdb...")
    results = [analyze_csv(c) for c in csvs]
    results.sort(key=lambda r: r.get("rows", 0), reverse=True)

    if args.top:
        results = results[:args.top]
        print(f"       Limiting to top {args.top}")

    ok_count = sum(1 for r in results if r["ok"])
    print(f"       Analyzed {ok_count}/{len(results)} successfully")

    print(f"[3/3] Writing report to {args.output}...")
    report = generate_report(results)
    Path(args.output).write_text(report, encoding="utf-8")
    print(f"       Done. Report: {Path(args.output).resolve()}")
    print(f"       Size: {len(report)} chars, {report.count(chr(10))+1} lines")


if __name__ == "__main__":
    main()
